version: 2.1
jobs:
  build:
    docker:
      - image: gillespelegrin/base-image
        environment:
          DB_HOST: postgresql://postgres@localhost/circle_test
          DB_USER: postgres
          DB_PASSWORD: postgres

      - image: cimg/postgres:14.0
        environment:
          PGHOST: localhost
          PGUSER: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: migrate
          command: npm run migrate:ci
      - run:
          name: E2E
          command: npm test
