version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.8.0
    steps:
      - checkout
      - run:
            name: install
            command: npm install
      - run:
          name: E2E
          command: npm test
